name: Run unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  MONGO_INITDB_ROOT_USERNAME: test
  MONGO_INITDB_ROOT_PASSWORD: password
  MONGO_INITDB_DATABASE: test
  DB_PORT: 27017

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:6.0
        env:
          MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
          MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
          MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
        ports:
          - ${DB_PORT}:${DB_PORT}
        options: >-
          --health-cmd mongo
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: make test
